### ISSUE TITLE
OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by Estel-Kitsune** [biocore-ntnu/epic#26]
Hi,

I'm using SICER in one of my projects, and I wanted to give epic a try. I'm using epic 0.0.6 (conda install). I downloaded the test.bed and control.bed files.

`epic --treatment test.bed --control control.bed`

And I'm getting the following error message:

> Merging ChIP and Input data. (File: helper_functions, Log level: INFO, Time: Mon, 18 Jul 2016 17:07:42 )
> 2290813547.42effective_genome_length (File: compute_background_probabilites, Log level: DEBUG, Time: Mon, 18 Jul 2016 17:07:42 )
> 200 window size (File: compute_background_probabilites, Log level: DEBUG, Time: Mon, 18 Jul 2016 17:07:42 )
> 0 total chip count (File: compute_background_probabilites, Log level: DEBUG, Time: Mon, 18 Jul 2016 17:07:42 )
> 0.0average_window_readcount (File: compute_background_probabilites, Log level: DEBUG, Time: Mon, 18 Jul 2016 17:07:42 )
> 1island_enriched_threshold (File: compute_background_probabilites, Log level: DEBUG, Time: Mon, 18 Jul 2016 17:07:42 )
> 4.0gap_contribution (File: compute_background_probabilites, Log level: DEBUG, Time: Mon, 18 Jul 2016 17:07:42 )
> 1.0boundary_contribution (File: compute_background_probabilites, Log level: DEBUG, Time: Mon, 18 Jul 2016 17:07:42 )
> Traceback (most recent call last):
>   File "/home/estelle/miniconda2/bin/epic", line 4, in <module>
>     **import**('pkg_resources').run_script('bioepic==0.0.6', 'epic')
>   File "/home/estelle/miniconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/**init**.py", line 726, in run_script
>   File "/home/estelle/miniconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/**init**.py", line 1491, in run_script
>   File "/home/estelle/miniconda2/lib/python2.7/site-packages/bioepic-0.0.6-py2.7.egg/EGG-INFO/scripts/epic", line 130, in <module>
> 
>   File "/pica/h1/estelle/miniconda2/lib/python2.7/site-packages/bioepic-0.0.6-py2.7.egg/epic/run/run_epic.py", line 38, in run_epic
>   File "/pica/h1/estelle/miniconda2/lib/python2.7/site-packages/bioepic-0.0.6-py2.7.egg/epic/statistics/compute_background_probabilites.py", line 59, in compute_background_probabilities
>   File "/pica/h1/estelle/miniconda2/lib/python2.7/site-packages/bioepic-0.0.6-py2.7.egg/epic/statistics/compute_score_threshold.py", line 24, in compute_score_threshold
> OverflowError: cannot convert float infinity to integer

/Estelle

**Comment by endrebak** [comment]
Try the latest version please. Epic is not stable yet and each upgrade fixes bugs :)

**Comment by endrebak** [comment]
It claims that there were no reads in the treatment file. See if that persists after upgrading, or if the file is empty.

**Comment by Estel-Kitsune** [comment]
There was a problem with the BED files (not on your repo, it was my mistake).
I've updated to version 0.1.1. and it seems to work fine with the example dataset.
Thanks! I'm closing this issue.
PS: When you have time, could you document the commands that are needed to run epic after cloning the git repository?

**Comment by endrebak** [comment]
Will do. Reopening as a reminder 👍
