### ISSUE TITLE
How to direct output to a file

### ISSUE THREAD

**Issue by abhisheksinghnl** [biocore-ntnu/epic#37]
Hi,

Strangely, I cannot save the output file. 

I cannot even find a parameter that says something on naming output file  :(

The output just displays on screen

How can I direct the output to files.

The command that I am using is 

 epic -t ChIPseq_H3K9me2.bed -c ChIPseq_input.bed -gn rn6

Thank you in advance.

**Comment by ksiklenka** [comment]
epic -t ChIPseq_H3K9me2.bed -c ChIPseq_input.bed -gn rn6 > dir/output.txt

**Comment by endrebak** [comment]
You can use the redirection operator ">" like so:

epic -t ChIPseq_H3K9me2.bed -c ChIPseq_input.bed -gn rn6 > yourfile.csv
It is great that you asked about this, I should add a note in the docs.
