### ISSUE TITLE
Effective Genome Size

### ISSUE THREAD

**Issue by c-guzman** [biocore-ntnu/epic#51]
As part of a pipeline I am using your epic-effective script to calculate EGS prior to downstream analysis. I was going through your arguments and noticed that your `-egs` parameter requires a EGS between 0 and 1. As opposed to the typical ~2.8 billion that is used by macs2 and deeptools for human hg38. I tried running epic with the 2.8 billion number and didn't run into any errors. 

Is this just because the parameter information is outdated or will this result in incorrect peak calling? I'm interested in knowing if i'll have to parse out extra information or if what I already have done is fine.

Thanks!

**Comment by endrebak** [comment]
Egs: effective size divided by actual size. It is the same as the original
SICER uses.

I should add an error if the EGS is bigger than one.

**Comment by c-guzman** [comment]
Great, thank you!
