### ISSUE TITLE
Use unique filenames for --sum-bigwig option

### ISSUE THREAD

**Issue by quantumdot** [biocore-ntnu/epic#53]
Running epic on multiple datasets with the same parameter directory location for `--sum-bigwig` will overwrite output of a previous run on a different dataset. It looks like the output file just get called `chip_sum.bw` and `input_sum.bw`. Can you change this to have a more unique name, perhaps by taking a `--name` parameter on the command line for an experiment name?

**Comment by endrebak** [comment]
I might do that in the future when I have more time. I see it as a preferable option to my current way of doing it, but for now you could just create a different folder for each experiment, so they are called `experiment1/chip_sum.bigwig` and `experiment2/chip_sum.bigwig` and so on.

**Comment by endrebak** [comment]
There are now three bigwig options (chip, input, log2fc) in 0.2.2 which is out in pypi (and I'm adding it to bioconda now).
