### ISSUE TITLE
total_genome_length is not defined

### ISSUE THREAD

**Issue by frymor** [biocore-ntnu/epic#58]
Thanks for updating the log and output options so fast. 
Now I get a different error though. 
I am using the same command as before 
```
epic --control wt.input.4h.1.reads.bedpe wt.input.4h.2.reads.bedpe --treatment wt.ip.4h.1.reads.bedpe wt.ip.4h.2.reads.bedpe -cpu 10 --genome sacCer3 -egf 0.961651807729 -cs Sc.R64.1.genome -b wt.input.4h.bed -bw wt.input.4h -sbw  wt.input.4h
```
Iam using a ```chromsize``` file, as saccharomyces cerevisiae is not (yet?) defined in your list of genomes, (besides I am using the ensembl annotations and not UCSC)

When running the newest version now (0.2.0), I amgetting the following error

```
# epic --control wt.input.4h.1.reads.bedpe wt.input.4h.2.reads.bedpe --treatment wt.ip.4h.1.reads.bedpe wt.ip.4h.2.reads.bedpe -cpu 10 --genome sacCer3 -egf 0.961651807729 -cs Sc.R64.1.genome -b wt.input.4h.bed -bw wt.input.4h -sbw wt.input.4h # epic_version: 0.2.0, pandas_version: 0.20.2 (File: epic, Log level: INFO, Time: Thu, 20 Jul 2017 07:53:32 )
Traceback (most recent call last):
  File "/usr/local/bin/epic", line 257, in <module>
    total_genome_length *= sum(args.chromosome_sizes.values())
NameError: name 'total_genome_length' is not defined
```

Any Ideas, why is this happening?
Assa

PS 
Do I need to use the ```--genome``` option at all in this case, if I supply a ```chromsize``` file?

**Comment by endrebak** [comment]
I'm fixing it now.

I'll also write some tests so this does not happen again.

Thanks for reporting. Update 0.2.1 is ready in PyPI will add to bioconda
now.

Endre
