### ISSUE TITLE
i2bw correction in the doc

### ISSUE THREAD

**Issue by frymor** [biocore-ntnu/epic#61]
Hi,
in the [documentation for the i2bw](http://bioepic.readthedocs.io/en/latest/output_files.html#i2bw-individual-log2fc-bigwigs) you're writing
`**-i2bw/–individual-log2fc-bigwigs**

This flag takes a folder to store bigwigs in. One bigwig file is created per bed/bedpe file given for epic to analyze.  ...`

I assume this was copied from the [bed file description](http://bioepic.readthedocs.io/en/latest/output_files.html#b-bed-optional). 

But don't you mean it creates one bigwig file for each Chip-file? 
It doesn't make sense to do it for the input files (and it doesn't create them anyway).

Assa

**Comment by endrebak** [comment]
Yes, good catch. Thanks!
