### ISSUE TITLE
Can we run Epic without a control file?

### ISSUE THREAD

**Issue by CodeInTheSkies** [biocore-ntnu/epic#62]
Hi there,

I have ChIP data for H3K27me3, but the biologist did not do a ChIP control experiment.  So, I don't have a matching control file.  When I tried to run epic, it crashed and threw an error saying it requires a control file.

Is it not possible at all to run epic without a control file?

I searched online, and for histone marks, many people say epic (SICER) is better, although MACS 2 seems to also have the ability to process broad peaks, possibly histone marks.

Anyway, please let me know if I can still run epic without controls.  Otherwise, I think I have no choice but to go for MACS?

Thanks a lot!

**Comment by endrebak** [comment]
You need to use macs2 :)

**Comment by endrebak** [comment]
Or the original sicer... Google sicerpy
