### ISSUE TITLE
Genome request

### ISSUE THREAD

**Issue by sejmodha** [biocore-ntnu/epic#65]
Hi There,

I am trying to use epic for ChiPSeq data for a genome that does not exist in the current list of the available genomes. It is possible to use epic in such cases?

```
Genome PbergheiANKA not found
If yours is not there, please request it at github.com/endrebak/epic . (File: genomes, Log level: ERROR, Time: Tue, 31 Oct 2017 15:21:05 )
```

I would like to request the [Plasmodium genome](http://plasmodb.org/common/downloads/Current_Release/PbergheiANKA/fasta/data/PlasmoDB-34_PbergheiANKA_Genome.fasta) be added to the list. 

Thanks

**Comment by endrebak** [comment]
Yes, you can use the —chromsizes flag and the —effective genome size flag together. Does the plasmodium genome have a UCSC code? If not I need to think hard about how to add it.

**Comment by endrebak** [comment]
Thanks for the request btw.

**Comment by sejmodha** [comment]
Thanks for the clarification, I have managed to run epic with the custom genome. I am not sure if UCSC code exists for this particular genome.

Thanks for your help once again.

**Comment by endrebak** [comment]
Super! The egs should just change how many regions are diff enriched, so it
does not matter that much. The most interesting regions will always be the
lowest fdr.
