### ISSUE TITLE
epic - bed formats

### ISSUE THREAD

**Issue by sejmodha** [biocore-ntnu/epic#67]
Hi There,

I have used epic for ChIP-Seq data and now I want to annotate peaks using peak annotation program e.g. annotatePeaks (from Homer), could you please explain the epic's default output format and the bed format generated using -b flag as the bed file does not have strand or peak ID info in it.

**Comment by endrebak** [comment]
I'd love to help you make the output homer-compatible. What do you need the data to look like? Each enriched regions (peak) (is a separate line in the bed). ChIP-Seq data is typically not stranded, and the epic data is not: the counts from each strand are merged into each peak. `.` is a common way of writing "no info" in bed files.  

The bed epic writes is especially tailored for use in the UCSC genome browser.

This describes the bed epic produces: http://bioepic.readthedocs.io/en/latest/output_files.html#b-bed-optional

The example bed is here for some reason: http://bioepic.readthedocs.io/en/latest/output_files.html#i2bw-individual-log2fc-bigwigs (I need to move it to the right section :/ )

**Comment by sejmodha** [comment]
I see! that makes sense, sorry I didn't visit the readthedocs page.  
I can re-format the data to be in the specific format required by annotatePeaks http://homer.ucsd.edu/homer/ngs/annotation.html.
Thanks for the prompt response.
