### ISSUE TITLE
run epic without control samples

### ISSUE THREAD

**Issue by james-chuang** [biocore-ntnu/epic#77]
Hello,

I'm interested in trying epic on some ChIP-exo and ChIP-nexus datasets. Unlike traditional ChIP-seq, these protocols don't generate an input library, which is a problem since epic requires control libraries to be specified in order to run.

Is it possible to make the control samples optional? [Section 2.1.5 of the 2009 SICER paper](https://academic.oup.com/bioinformatics/article/25/15/1952/212783) is about using a random background model in the absence of a control library.

**Comment by endrebak** [comment]
Perhaps https://github.com/dariober/SICERpy does what you want? Or MACS2? I have no plans of adding support for ChIP only as I do not have the time and do not need it myself, unfortunately.

I gain nothing for having made epic publically available and can't really spend much time on it except for the stuff that I need. Sorry!

**Comment by james-chuang** [comment]
No worries!

The option is available using SICER itself, so between that and SICERpy I'll be able to get what I need. Just thought I'd ask since epic looked like the most user-friendly/maintained project of the three.
