### ISSUE TITLE
problem with output

### ISSUE THREAD

**Issue by lucacozzuto** [biocore-ntnu/epic#82]
Dear developers,
I'm using epic on a custom genome and I got a strange way to report the chromosomes:

Chromosome Start End ChIP Input Score Log2FC P FDR
1.0 3444800 3448199 76 31 46.45753848688762 1.3234133686618605 1.0186276074296772e-12 1.6867722789083852e-12
1.0 4773200 4777399 251 59 215.2449786380842 2.1185826701940806 5.0498235300167793e-79 2.9157875286298807e-78
1.0 4786400 4787599 37 8 29.947537650660315 2.2391355312341 8.964265400850882e-15 1.6083926773604145e-14

 
The genome sizes used are instead 1, 2, 3 etc...

Luca

**Comment by endrebak** [comment]
Do you mean chromosome names? Should be 1, 1, 1 instead of 1.0, 1.0, 1.0 in the first column?

Anyways, thanks for reporting. If you can elaborate I'll try to get to the bottom of your problem.

**Comment by lucacozzuto** [comment]
yes. I don't understand why I get 1.0 instead of just 1...

**Comment by endrebak** [comment]
Thank you. I'll fix this tomorrow. :)

**Comment by lucacozzuto** [comment]
thanks a lot!

**Comment by endrebak** [comment]
I just uploaded epic 0.2.10 to PyPI. The new version is more mem-efficient, but requires pandas>=0.23.0.

There was another bug in the script so your results should also hopefully be different.

Try `pip install bioepic==0.2.10`.

**Comment by lucacozzuto** [comment]
Thank you!

**Comment by endrebak** [comment]
If something does not work, feel free to reopen. Thank you for bothering to report :)
