### ISSUE TITLE
conda still installs 0.2.9

### ISSUE THREAD

**Issue by avilella** [biocore-ntnu/epic#84]
I am trying to install EPIC on an Ubuntu 16.04 using MiniConda and the conda method described in the README, and it seems it's pulling version 0.2.9.

Is there a conda-aware way of installing the newer 0.2.11 version, which seems important given the speed-up in the Changelog:
```
# 0.2.11 (01.08.18)
- Massive speedup with Cython
- Fix bugs added by 0.2.10
```

**Comment by endrebak** [comment]
No, not yet. You can do pip install bioepic though :)

I'll get around to it eventually.

**Comment by endrebak** [comment]
Thanks for reporting btw. I am presenting a poster at Genome Informatics in your neck of the woods in two weeks. If you are going I'd love to hear what you use epic for.

**Comment by endrebak** [comment]
Added a PR: https://github.com/bioconda/bioconda-recipes/pull/10605

Will not be able to merge until tomorrow.

**Comment by endrebak** [comment]
It seems like there is a build error in the PR. Trying again.

Ps. It is the "Clustering bins into islands." part which is affected by the
speedup. Has gone from taking a minute to less than a second on my data.

**Comment by endrebak** [comment]
Bioconda update now hinges on sb helping me with this: https://github.com/bioconda/bioconda-recipes/issues/10636

**Comment by endrebak** [comment]
I was just able to update it to 0.2.12. Finding enriched islands now is down from a minute to a fraction of a second on my large datasets.

**Comment by endrebak** [comment]
Feel free to reopen if it does not work :)

**Comment by avilella** [comment]
Just reporting back that I managed to build epic 0.2.12 via conda on an Ubuntu 16.04 workstation, create a .tar.gz of the whole miniconda2 folder, then transfer to a DNAnexus instance, build an app and execute. It completed successfully.
